In [20]:
import numpy as np

In [21]:
arr= np.arange(0,30,3)

In [22]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [23]:
arr[3] #Indíce funciona como nas listas

9

In [24]:
arr[2:5]

array([ 6,  9, 12])

In [25]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [26]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [27]:
arr[2:]= 100

In [28]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr=  np.arange(50).reshape((5,10))

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
arr.shape

(5, 10)

In [32]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [33]:
arr2= arr[:3]

In [34]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [35]:
arr2[:]=100

In [36]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [41]:
arr2= arr[:3].copy()

Com o método copy o array original é copiado e qualquer alteração na cópia não influencia o array original

In [38]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [39]:
arr #o array 1 mudou também, pois o Python faz uma mera referência

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [42]:
arr[1:4, 5:]#linhas e colunas, da linha 1 até a 3, da coluna 5 em diante

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [43]:
arr > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]], dtype=bool)

In [44]:
bol= arr> 50

In [45]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [49]:
arr = np.linspace(0,100, 30)

In [51]:
arr.shape


(30,)

In [53]:
arr= arr.reshape(3,10)

In [54]:
arr

array([[   0.        ,    3.44827586,    6.89655172,   10.34482759,
          13.79310345,   17.24137931,   20.68965517,   24.13793103,
          27.5862069 ,   31.03448276],
       [  34.48275862,   37.93103448,   41.37931034,   44.82758621,
          48.27586207,   51.72413793,   55.17241379,   58.62068966,
          62.06896552,   65.51724138],
       [  68.96551724,   72.4137931 ,   75.86206897,   79.31034483,
          82.75862069,   86.20689655,   89.65517241,   93.10344828,
          96.55172414,  100.        ]])

In [55]:
arr[0:2, 2]

array([  6.89655172,  41.37931034])