In [2]:
import numpy as np

In [3]:
minha_lista=[1,2,3]

In [4]:
minha_lista

[1, 2, 3]

In [5]:
np.array(minha_lista) #converte uma lista num array

array([1, 2, 3])

In [8]:
minha_matriz=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(minha_matriz) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

É possível observar que a matriz possui 2 dimensões pela quantidade de colchetes

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Cria uma lista de 0 a 10 contando de 2 em 2, somente os números pares, arange é um método semelhante ao range

In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
arr= np.zeros(3)

In [14]:
arr

array([ 0.,  0.,  0.])

In [15]:
arr= np.zeros((5,5))

In [16]:
arr

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

Cria-se uma matriz através de uma tupla, pode-se obversar que a matriz possui 2 dimensões pelas chaves

In [17]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

Matriz identidade, 1 na diagonal 

In [19]:
np.linspace(0,10,2)

array([  0.,  10.])

In [20]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

Cria uma lista com autopreenchimento como o range, mas diferente di range você pode especificar quantos números quer ver 


In [21]:
np.random.rand(5)

array([ 0.75838834,  0.54832266,  0.01167378,  0.57433539,  0.59014894])

In [22]:
np.random.rand(5)*100

array([ 56.37099558,  73.80853639,  80.15235331,  87.63545528,   5.65060652])

In [24]:
np.random.rand(5,4,3)

array([[[ 0.9460955 ,  0.22026981,  0.39963789],
        [ 0.45919057,  0.08535914,  0.87976067],
        [ 0.85477483,  0.46000996,  0.45869393],
        [ 0.53868824,  0.76571918,  0.18254746]],

       [[ 0.92587427,  0.54069686,  0.81018919],
        [ 0.98312759,  0.18373373,  0.15701952],
        [ 0.56486508,  0.03828746,  0.19694143],
        [ 0.31700126,  0.60531671,  0.92488721]],

       [[ 0.2765335 ,  0.46662893,  0.98365848],
        [ 0.08669121,  0.39707367,  0.79629004],
        [ 0.89951949,  0.67917355,  0.91172442],
        [ 0.9333568 ,  0.01200341,  0.88707827]],

       [[ 0.1817862 ,  0.75688806,  0.23831851],
        [ 0.08441888,  0.0653384 ,  0.71881492],
        [ 0.36206053,  0.57528854,  0.60208067],
        [ 0.83649913,  0.34734139,  0.89842693]],

       [[ 0.87172572,  0.28555714,  0.45556369],
        [ 0.74550821,  0.37043443,  0.78047637],
        [ 0.64687782,  0.02955315,  0.34114573],
        [ 0.40235729,  0.11852335,  0.68758872]]])

In [26]:
np.random.randn(4)

array([ 1.51411009, -1.37122418,  1.70489674, -0.70300708])

In [27]:
np.random.randint(0,100,10)

array([93, 57, 22, 58,  4, 15, 34, 44, 35, 74])

In [31]:
np.random.rand(5)*100

array([  1.68993344,  39.1933229 ,  18.10087253,  11.52196481,   3.6250011 ])

In [32]:
np.round(np.random.rand(5), 0)

array([ 1.,  0.,  0.,  1.,  0.])

In [34]:
np.round(np.random.rand(5)*100, 0)

array([ 77.,  65.,  63.,  64.,  77.])

In [40]:
arr= np.random.rand(25)

In [41]:
arr.shape

(25,)

In [36]:
arr

array([ 0.33619056,  0.78367499,  0.57059556,  0.33148462,  0.70236948,
        0.93854154,  0.26500416,  0.66325594,  0.6864146 ,  0.65039728,
        0.03471748,  0.44361307,  0.97900832,  0.88575857,  0.92606472,
        0.68673806,  0.76677543,  0.48406222,  0.83619974,  0.1963676 ,
        0.71486104,  0.74261074,  0.58607523,  0.33357955,  0.61936226])

In [45]:
arr= arr.reshape((5,5))

In [46]:
arr

array([[ 0.67139901,  0.19399829,  0.44837766,  0.69729227,  0.00913951],
       [ 0.66711713,  0.99045119,  0.57756715,  0.5453161 ,  0.1403905 ],
       [ 0.39370944,  0.96743605,  0.75420705,  0.71463655,  0.89099008],
       [ 0.7991666 ,  0.53941669,  0.18823333,  0.55331939,  0.00327614],
       [ 0.22316153,  0.80618482,  0.14445402,  0.35938809,  0.86949423]])

In [43]:
arr.shape

(5, 5)

In [47]:
arr.max()

0.99045118967629542

In [48]:
arr.min()

0.0032761392102191866

In [49]:
arr.argmax()

6

In [50]:
arr.argmin()

19